spring:
    profiles:
        active:
        - dev
---    
spring:
    profiles: dev
    application:
        name: microservice-cloud-config-dev
---        
spring:
    profiles: test
    application:
        name: microservice-cloud-config-test
#as UTF-8 saved